### ISSUE TITLE
Add an example code to README.md that handles errors thrown by the require function

### ISSUE THREAD

**Issue by Densyakun** [nicebro/node-hmr#19]
- node-hmr only monitors modules added to require.cache.
- If an error is thrown in the require function, the module is removed from require.cache.
- When it catches an error thrown by the require function, it continues monitoring by adding that module to require.cache.

`test.js`:

```js
const path = require('path')
const hmr = require('node-hmr')

var watchDir = './'
var handleFile = './handle.js'

hmr(() => {
  try {
    require(handleFile)
  } catch (e) {
    console.error(e)
    const moduleId = path.resolve(watchDir, handleFile)
    require.cache[moduleId] = { id: moduleId }
  }
  console.log('handle!')
}, { watchDir: watchDir, watchFilePatterns: [handleFile] })
```

`handle.js`:

```js
\
```

console:

```bash
handle.js:1
\
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at HMR.hmr.watchDir [as callback] (test.js:9:5)
    at HMR.init (node-hmr@1.3.1\node_modules\node-hmr\index.js:74:10)
    at Object.<anonymous> (test.js:5:1)
handle!
```

When the `handle.js` file is changed, the message "handle!" is displayed correctly.

**Comment by serhiinkh** [comment]
@Densyakun Thanks, will add improvement soon
